"""
PDF report generator for dermatology diagnoses.
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
from typing import Dict, Optional
import os
import uuid

from backend.app.core.config import settings
from backend.app.core.logging import get_logger

logger = get_logger(__name__)


class PDFReportGenerator:
    """Generate professional dermatology diagnosis reports."""
    
    def __init__(self):
        """Initialize PDF generator."""
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a237e'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#283593'),
            spaceAfter=12,
            spaceBefore=12
        ))
    
    def generate_report(
        self,
        diagnosis_data: Dict,
        patient_info: Dict,
        output_filename: Optional[str] = None
    ) -> str:
        """
        Generate comprehensive dermatology report.
        
        Args:
            diagnosis_data: Diagnosis information
            patient_info: Patient demographics
            output_filename: Custom output filename
        
        Returns:
            Path to generated PDF
        """
        try:
            # Generate filename
            if not output_filename:
                report_id = str(uuid.uuid4())[:8]
                output_filename = f"dermatology_report_{report_id}.pdf"
            
            output_path = os.path.join(settings.REPORT_DIR, output_filename)
            os.makedirs(settings.REPORT_DIR, exist_ok=True)
            
            # Create PDF document
            doc = SimpleDocTemplate(output_path, pagesize=letter)
            story = []
            
            # Title
            title = Paragraph("Dermatology AI Analysis Report", self.styles['CustomTitle'])
            story.append(title)
            story.append(Spacer(1, 0.3 * inch))
            
            # Report metadata
            report_date = datetime.now().strftime("%B %d, %Y %I:%M %p")
            metadata = Paragraph(
                f"<b>Report Date:</b> {report_date}<br/>"
                f"<b>Report ID:</b> {diagnosis_data.get('id', 'N/A')}",
                self.styles['Normal']
            )
            story.append(metadata)
            story.append(Spacer(1, 0.3 * inch))
            
            # Medical Disclaimer
            disclaimer = Paragraph(
                "<b>MEDICAL DISCLAIMER:</b> This report is generated by an AI system and is intended "
                "to assist healthcare professionals. It should NOT be used as a sole diagnostic tool. "
                "All findings must be reviewed and confirmed by a qualified dermatologist.",
                ParagraphStyle(
                    name='Disclaimer',
                    parent=self.styles['Normal'],
                    textColor=colors.red,
                    fontSize=9,
                    italic=True
                )
            )
            story.append(disclaimer)
            story.append(Spacer(1, 0.4 * inch))
            
            # Patient Information
            story.append(Paragraph("Patient Information", self.styles['SectionHeader']))
            patient_data = [
                ['Name:', patient_info.get('name', 'N/A')],
                ['Date of Birth:', str(patient_info.get('date_of_birth', 'N/A'))],
                ['Gender:', patient_info.get('gender', 'N/A')],
                ['Skin Type:', patient_info.get('skin_type', 'N/A')]
            ]
            patient_table = Table(patient_data, colWidths=[2*inch, 4*inch])
            patient_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 1, colors.grey)
            ]))
            story.append(patient_table)
            story.append(Spacer(1, 0.3 * inch))
            
            # AI Diagnosis
            story.append(Paragraph("AI Diagnosis", self.styles['SectionHeader']))
            diagnosis = diagnosis_data.get('diagnosis', {})
            diag_text = (
                f"<b>Primary Prediction:</b> {diagnosis.get('primary_prediction', 'N/A')}<br/>"
                f"<b>Confidence Score:</b> {diagnosis.get('confidence', 0):.1%}<br/>"
                f"<b>Risk Level:</b> {diagnosis_data.get('risk_level', 'N/A').upper()}"
            )
            story.append(Paragraph(diag_text, self.styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))
            
            # ABCDE Analysis
            if diagnosis_data.get('abcde_scores'):
                story.append(Paragraph("ABCDE Analysis", self.styles['SectionHeader']))
                abcde = diagnosis_data['abcde_scores']
                abcde_data = [
                    ['Criterion', 'Score', 'Interpretation'],
                    ['Asymmetry', f"{abcde.get('asymmetry', 0):.2f}", self._interpret_score(abcde.get('asymmetry', 0))],
                    ['Border', f"{abcde.get('border', 0):.2f}", self._interpret_score(abcde.get('border', 0))],
                    ['Color', f"{abcde.get('color', 0):.2f}", self._interpret_score(abcde.get('color', 0))],
                    ['Diameter', f"{abcde.get('diameter_mm', 0):.1f} mm", 'Normal' if abcde.get('diameter_mm', 0) < 6 else 'Elevated'],
                ]
                abcde_table = Table(abcde_data, colWidths=[2*inch, 1.5*inch, 2.5*inch])
                abcde_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#283593')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 1, colors.grey)
                ]))
                story.append(abcde_table)
                story.append(Spacer(1, 0.3 * inch))
            
            # Recommendation
            story.append(Paragraph("Recommendation", self.styles['SectionHeader']))
            recommendation = Paragraph(
                diagnosis_data.get('recommendation', 'Consult with a dermatologist.'),
                self.styles['Normal']
            )
            story.append(recommendation)
            story.append(Spacer(1, 0.3 * inch))
            
            # Add visualization if available
            if diagnosis_data.get('gradcam_path') and os.path.exists(diagnosis_data['gradcam_path']):
                story.append(Paragraph("Grad-CAM Visualization", self.styles['SectionHeader']))
                try:
                    img = Image(diagnosis_data['gradcam_path'], width=4*inch, height=4*inch)
                    story.append(img)
                except Exception as e:
                    logger.error(f"Error adding image to PDF: {e}")
            
            # Footer
            story.append(Spacer(1, 0.5 * inch))
            footer = Paragraph(
                "<i>This report was generated by the Dermatology AI Assistant. "
                "For questions or concerns, please consult with a qualified healthcare professional.</i>",
                ParagraphStyle(
                    name='Footer',
                    parent=self.styles['Normal'],
                    fontSize=8,
                    textColor=colors.grey,
                    alignment=TA_CENTER
                )
            )
            story.append(footer)
            
            # Build PDF
            doc.build(story)
            logger.info(f"PDF report generated: {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"Error generating PDF report: {e}")
            raise
    
    def _interpret_score(self, score: float) -> str:
        """Interpret ABCDE score."""
        if score < 0.3:
            return "Low"
        elif score < 0.7:
            return "Moderate"
        else:
            return "High"


# Global generator instance
_pdf_generator = None


def get_pdf_generator() -> PDFReportGenerator:
    """Get or create global PDF generator instance."""
    global _pdf_generator
    if _pdf_generator is None:
        _pdf_generator = PDFReportGenerator()
    return _pdf_generator
